metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
  reload.period: 10s

metricbeat.modules:
  # Мониторинг системных метрик хоста
  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - diskio
      - filesystem
    enabled: true
    period: 10s
    processes: ['.*']
    hostfs: "/hostfs"

  # Мониторинг Docker
  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    enabled: true
    period: 15s

  # Сбор метрик Prometheus из Go API
  - module: prometheus
    metricsets: ["collector"]
    hosts: ["http://go-api:8080"]  # Внутри Docker сети
    metrics_path: "/metrics"
    enabled: true
    period: 15s
    use_types: true
    rate_counters: true
    namespace: "go_api"

processors:
  - add_host_metadata:
      netinfo.enabled: true
      cache.ttl: 5m
      geo:
        name: geoip
        fields:
          - ip
  
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  
  - add_fields:
      fields:
        environment: "production"
        server_ip: "147.45.183.143"
        location: "production-server"
  
  - add_tags:
      tags: ["go-api", "production", "server-147.45.183.143"]

# Вывод в Elasticsearch
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]  # Внутри Docker сети
  
  indices:
    - index: "metrics-system-%{+yyyy.MM.dd}"
      when.equals:
        metricset.module: "system"
    
    - index: "metrics-docker-%{+yyyy.MM.dd}"
      when.equals:
        metricset.module: "docker"
    
    - index: "metrics-goapi-%{+yyyy.MM.dd}"
      when.equals:
        metricset.module: "prometheus"

# Логирование
logging:
  level: info
  to_files: true
  files:
    path: /usr/share/metricbeat/logs
    name: metricbeat.log
    keepfiles: 7
    permissions: 0644

# Мониторинг самого Metricbeat
monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]

# Настройки Kibana дашбордов
setup.kibana:
  host: "http://kibana:5601"

setup.dashboards.enabled: true